/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pap.ass06;

import java.awt.Color;
import javax.swing.JTextField;
import java.util.Random;

/**
 *
 * @author luca.parisi2
 */
public class form extends javax.swing.JFrame {

    Controller c;
    JTextField[][] matrix; //matrice di celle viste nella form
    Point[][] cells; //matrice di celle da computare (n > matrix.length)
    FlagMonitor flag;
    final int points_size = 10; //sono matrici quadrate
    final int matrix_size = 10;
    int howMany = 0;
    
    /**
     * Creates new form form
     */
    public form() {
        initComponents();
        
        //genera random 100*100 point, la matrice fa vedere i primi 10*10 
        Random r = new Random(System.currentTimeMillis());
        cells = new Point[points_size][points_size];
        for(int i = 0; i < points_size; i++)
        {
            for(int j = 0; j < points_size; j++)
            {
                int n = r.nextInt(2);
                cells[i][j] = new Point(i, j, n == 0 ? Life.Dead : Life.Live);
            }
        }
        
        //assegno la matrice di textbox, è la porzione di Point vista nella form
        matrix = new JTextField[][]
                {
                    {txt11, txt12, txt13, txt14, txt15, txt16, txt17, txt18, txt19, txt110},
                    {txt21, txt22, txt23, txt24, txt25, txt26, txt27, txt28, txt29, txt210},
                    {txt31, txt32, txt33, txt34, txt35, txt36, txt37, txt38, txt39, txt310},
                    {txt41, txt42, txt43, txt44, txt45, txt46, txt47, txt48, txt49, txt410},
                    {txt51, txt52, txt53, txt54, txt55, txt56, txt57, txt58, txt59, txt510},
                    {txt61, txt62, txt63, txt64, txt65, txt66, txt67, txt68, txt69, txt610},
                    {txt71, txt72, txt73, txt74, txt75, txt76, txt77, txt78, txt79, txt710},
                    {txt81, txt82, txt83, txt84, txt85, txt86, txt87, txt88, txt89, txt810},
                    {txt91, txt92, txt93, txt94, txt95, txt96, txt97, txt98, txt99, txt910},
                    {txt101, txt102, txt103, txt104, txt105, txt106, txt107, txt108, txt109, txt1010}
                };
        
        howMany = Runtime.getRuntime().availableProcessors() + 2;
        flag = new FlagMonitor();        
        c = new Controller(howMany, matrix, matrix_size, matrix_size, cells, points_size, points_size, flag, jLabel1);
        c.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt11 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        txt13 = new javax.swing.JTextField();
        txt14 = new javax.swing.JTextField();
        txt15 = new javax.swing.JTextField();
        txt16 = new javax.swing.JTextField();
        txt17 = new javax.swing.JTextField();
        txt18 = new javax.swing.JTextField();
        txt19 = new javax.swing.JTextField();
        txt110 = new javax.swing.JTextField();
        txt21 = new javax.swing.JTextField();
        txt22 = new javax.swing.JTextField();
        txt23 = new javax.swing.JTextField();
        txt24 = new javax.swing.JTextField();
        txt25 = new javax.swing.JTextField();
        txt26 = new javax.swing.JTextField();
        txt27 = new javax.swing.JTextField();
        txt28 = new javax.swing.JTextField();
        txt29 = new javax.swing.JTextField();
        txt210 = new javax.swing.JTextField();
        txt31 = new javax.swing.JTextField();
        txt32 = new javax.swing.JTextField();
        txt33 = new javax.swing.JTextField();
        txt34 = new javax.swing.JTextField();
        txt35 = new javax.swing.JTextField();
        txt36 = new javax.swing.JTextField();
        txt37 = new javax.swing.JTextField();
        txt38 = new javax.swing.JTextField();
        txt39 = new javax.swing.JTextField();
        txt310 = new javax.swing.JTextField();
        txt41 = new javax.swing.JTextField();
        txt42 = new javax.swing.JTextField();
        txt43 = new javax.swing.JTextField();
        txt44 = new javax.swing.JTextField();
        txt45 = new javax.swing.JTextField();
        txt46 = new javax.swing.JTextField();
        txt47 = new javax.swing.JTextField();
        txt48 = new javax.swing.JTextField();
        txt49 = new javax.swing.JTextField();
        txt410 = new javax.swing.JTextField();
        txt51 = new javax.swing.JTextField();
        txt52 = new javax.swing.JTextField();
        txt53 = new javax.swing.JTextField();
        txt54 = new javax.swing.JTextField();
        txt55 = new javax.swing.JTextField();
        txt56 = new javax.swing.JTextField();
        txt57 = new javax.swing.JTextField();
        txt58 = new javax.swing.JTextField();
        txt59 = new javax.swing.JTextField();
        txt510 = new javax.swing.JTextField();
        txt61 = new javax.swing.JTextField();
        txt62 = new javax.swing.JTextField();
        txt63 = new javax.swing.JTextField();
        txt64 = new javax.swing.JTextField();
        txt65 = new javax.swing.JTextField();
        txt66 = new javax.swing.JTextField();
        txt67 = new javax.swing.JTextField();
        txt68 = new javax.swing.JTextField();
        txt69 = new javax.swing.JTextField();
        txt610 = new javax.swing.JTextField();
        txt71 = new javax.swing.JTextField();
        txt72 = new javax.swing.JTextField();
        txt73 = new javax.swing.JTextField();
        txt74 = new javax.swing.JTextField();
        txt75 = new javax.swing.JTextField();
        txt76 = new javax.swing.JTextField();
        txt77 = new javax.swing.JTextField();
        txt78 = new javax.swing.JTextField();
        txt79 = new javax.swing.JTextField();
        txt710 = new javax.swing.JTextField();
        txt81 = new javax.swing.JTextField();
        txt82 = new javax.swing.JTextField();
        txt83 = new javax.swing.JTextField();
        txt84 = new javax.swing.JTextField();
        txt85 = new javax.swing.JTextField();
        txt86 = new javax.swing.JTextField();
        txt87 = new javax.swing.JTextField();
        txt88 = new javax.swing.JTextField();
        txt89 = new javax.swing.JTextField();
        txt810 = new javax.swing.JTextField();
        txt91 = new javax.swing.JTextField();
        txt92 = new javax.swing.JTextField();
        txt93 = new javax.swing.JTextField();
        txt94 = new javax.swing.JTextField();
        txt95 = new javax.swing.JTextField();
        txt96 = new javax.swing.JTextField();
        txt97 = new javax.swing.JTextField();
        txt98 = new javax.swing.JTextField();
        txt99 = new javax.swing.JTextField();
        txt910 = new javax.swing.JTextField();
        txt101 = new javax.swing.JTextField();
        txt102 = new javax.swing.JTextField();
        txt103 = new javax.swing.JTextField();
        txt104 = new javax.swing.JTextField();
        txt105 = new javax.swing.JTextField();
        txt106 = new javax.swing.JTextField();
        txt107 = new javax.swing.JTextField();
        txt108 = new javax.swing.JTextField();
        txt109 = new javax.swing.JTextField();
        txt1010 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(10, 10));
        jPanel1.add(txt11);
        jPanel1.add(txt12);
        jPanel1.add(txt13);
        jPanel1.add(txt14);
        jPanel1.add(txt15);
        jPanel1.add(txt16);
        jPanel1.add(txt17);
        jPanel1.add(txt18);
        jPanel1.add(txt19);
        jPanel1.add(txt110);
        jPanel1.add(txt21);
        jPanel1.add(txt22);
        jPanel1.add(txt23);
        jPanel1.add(txt24);
        jPanel1.add(txt25);
        jPanel1.add(txt26);
        jPanel1.add(txt27);
        jPanel1.add(txt28);
        jPanel1.add(txt29);
        jPanel1.add(txt210);
        jPanel1.add(txt31);
        jPanel1.add(txt32);
        jPanel1.add(txt33);
        jPanel1.add(txt34);
        jPanel1.add(txt35);
        jPanel1.add(txt36);
        jPanel1.add(txt37);
        jPanel1.add(txt38);
        jPanel1.add(txt39);
        jPanel1.add(txt310);
        jPanel1.add(txt41);
        jPanel1.add(txt42);
        jPanel1.add(txt43);
        jPanel1.add(txt44);
        jPanel1.add(txt45);
        jPanel1.add(txt46);
        jPanel1.add(txt47);
        jPanel1.add(txt48);
        jPanel1.add(txt49);
        jPanel1.add(txt410);
        jPanel1.add(txt51);
        jPanel1.add(txt52);
        jPanel1.add(txt53);
        jPanel1.add(txt54);
        jPanel1.add(txt55);
        jPanel1.add(txt56);
        jPanel1.add(txt57);
        jPanel1.add(txt58);
        jPanel1.add(txt59);
        jPanel1.add(txt510);
        jPanel1.add(txt61);
        jPanel1.add(txt62);
        jPanel1.add(txt63);
        jPanel1.add(txt64);
        jPanel1.add(txt65);
        jPanel1.add(txt66);
        jPanel1.add(txt67);
        jPanel1.add(txt68);
        jPanel1.add(txt69);
        jPanel1.add(txt610);
        jPanel1.add(txt71);
        jPanel1.add(txt72);
        jPanel1.add(txt73);
        jPanel1.add(txt74);
        jPanel1.add(txt75);
        jPanel1.add(txt76);
        jPanel1.add(txt77);
        jPanel1.add(txt78);
        jPanel1.add(txt79);
        jPanel1.add(txt710);
        jPanel1.add(txt81);
        jPanel1.add(txt82);
        jPanel1.add(txt83);
        jPanel1.add(txt84);
        jPanel1.add(txt85);
        jPanel1.add(txt86);
        jPanel1.add(txt87);
        jPanel1.add(txt88);
        jPanel1.add(txt89);
        jPanel1.add(txt810);
        jPanel1.add(txt91);
        jPanel1.add(txt92);
        jPanel1.add(txt93);
        jPanel1.add(txt94);
        jPanel1.add(txt95);
        jPanel1.add(txt96);
        jPanel1.add(txt97);
        jPanel1.add(txt98);
        jPanel1.add(txt99);
        jPanel1.add(txt910);
        jPanel1.add(txt101);
        jPanel1.add(txt102);
        jPanel1.add(txt103);
        jPanel1.add(txt104);
        jPanel1.add(txt105);
        jPanel1.add(txt106);
        jPanel1.add(txt107);
        jPanel1.add(txt108);
        jPanel1.add(txt109);
        jPanel1.add(txt1010);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	//start
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        flag.start();
        
    }//GEN-LAST:event_jButton1ActionPerformed

	//stop
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        flag.stop();
        
    }//GEN-LAST:event_jButton2ActionPerformed

	//reset
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //genera random 100*100 point, la matrice fa vedere i primi 10*10 
        Random r = new Random(System.currentTimeMillis());
        cells = new Point[points_size][points_size];
        for(int i = 0; i < points_size; i++)
        {
            for(int j = 0; j < points_size; j++)
            {
                int n = r.nextInt(2);
                cells[i][j] = new Point(i, j, n == 0 ? Life.Dead : Life.Live);
                //resetto matrice form:
                if(i < matrix_size && j < matrix_size)
                {
                    matrix[i][j].setBackground(Color.WHITE);
                }                
            }
        }
        //creo un nuovo controller
        c.interrupt();
        c = new Controller(howMany, matrix, matrix_size, matrix_size, cells, points_size, points_size, flag, jLabel1);
        c.start();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });       
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt101;
    private javax.swing.JTextField txt1010;
    private javax.swing.JTextField txt102;
    private javax.swing.JTextField txt103;
    private javax.swing.JTextField txt104;
    private javax.swing.JTextField txt105;
    private javax.swing.JTextField txt106;
    private javax.swing.JTextField txt107;
    private javax.swing.JTextField txt108;
    private javax.swing.JTextField txt109;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt110;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt13;
    private javax.swing.JTextField txt14;
    private javax.swing.JTextField txt15;
    private javax.swing.JTextField txt16;
    private javax.swing.JTextField txt17;
    private javax.swing.JTextField txt18;
    private javax.swing.JTextField txt19;
    private javax.swing.JTextField txt21;
    private javax.swing.JTextField txt210;
    private javax.swing.JTextField txt22;
    private javax.swing.JTextField txt23;
    private javax.swing.JTextField txt24;
    private javax.swing.JTextField txt25;
    private javax.swing.JTextField txt26;
    private javax.swing.JTextField txt27;
    private javax.swing.JTextField txt28;
    private javax.swing.JTextField txt29;
    private javax.swing.JTextField txt31;
    private javax.swing.JTextField txt310;
    private javax.swing.JTextField txt32;
    private javax.swing.JTextField txt33;
    private javax.swing.JTextField txt34;
    private javax.swing.JTextField txt35;
    private javax.swing.JTextField txt36;
    private javax.swing.JTextField txt37;
    private javax.swing.JTextField txt38;
    private javax.swing.JTextField txt39;
    private javax.swing.JTextField txt41;
    private javax.swing.JTextField txt410;
    private javax.swing.JTextField txt42;
    private javax.swing.JTextField txt43;
    private javax.swing.JTextField txt44;
    private javax.swing.JTextField txt45;
    private javax.swing.JTextField txt46;
    private javax.swing.JTextField txt47;
    private javax.swing.JTextField txt48;
    private javax.swing.JTextField txt49;
    private javax.swing.JTextField txt51;
    private javax.swing.JTextField txt510;
    private javax.swing.JTextField txt52;
    private javax.swing.JTextField txt53;
    private javax.swing.JTextField txt54;
    private javax.swing.JTextField txt55;
    private javax.swing.JTextField txt56;
    private javax.swing.JTextField txt57;
    private javax.swing.JTextField txt58;
    private javax.swing.JTextField txt59;
    private javax.swing.JTextField txt61;
    private javax.swing.JTextField txt610;
    private javax.swing.JTextField txt62;
    private javax.swing.JTextField txt63;
    private javax.swing.JTextField txt64;
    private javax.swing.JTextField txt65;
    private javax.swing.JTextField txt66;
    private javax.swing.JTextField txt67;
    private javax.swing.JTextField txt68;
    private javax.swing.JTextField txt69;
    private javax.swing.JTextField txt71;
    private javax.swing.JTextField txt710;
    private javax.swing.JTextField txt72;
    private javax.swing.JTextField txt73;
    private javax.swing.JTextField txt74;
    private javax.swing.JTextField txt75;
    private javax.swing.JTextField txt76;
    private javax.swing.JTextField txt77;
    private javax.swing.JTextField txt78;
    private javax.swing.JTextField txt79;
    private javax.swing.JTextField txt81;
    private javax.swing.JTextField txt810;
    private javax.swing.JTextField txt82;
    private javax.swing.JTextField txt83;
    private javax.swing.JTextField txt84;
    private javax.swing.JTextField txt85;
    private javax.swing.JTextField txt86;
    private javax.swing.JTextField txt87;
    private javax.swing.JTextField txt88;
    private javax.swing.JTextField txt89;
    private javax.swing.JTextField txt91;
    private javax.swing.JTextField txt910;
    private javax.swing.JTextField txt92;
    private javax.swing.JTextField txt93;
    private javax.swing.JTextField txt94;
    private javax.swing.JTextField txt95;
    private javax.swing.JTextField txt96;
    private javax.swing.JTextField txt97;
    private javax.swing.JTextField txt98;
    private javax.swing.JTextField txt99;
    // End of variables declaration//GEN-END:variables
}
