/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lowerbound;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author luca
 */
public class LBGraph extends javax.swing.JFrame {

    /**
     * Creates new form LBGraph
     */
    public LBGraph() {
        super("Grafo Lower Bound");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlLowerBound = new javax.swing.JPanel();
        LblLB = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(732, 611));

        PnlLowerBound.setPreferredSize(new java.awt.Dimension(709, 563));

        javax.swing.GroupLayout PnlLowerBoundLayout = new javax.swing.GroupLayout(PnlLowerBound);
        PnlLowerBound.setLayout(PnlLowerBoundLayout);
        PnlLowerBoundLayout.setHorizontalGroup(
            PnlLowerBoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        PnlLowerBoundLayout.setVerticalGroup(
            PnlLowerBoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        LblLB.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        LblLB.setText("LowerBound");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PnlLowerBound, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlLowerBound, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPnlLB()
    {
        return PnlLowerBound;
    }
    
    public JLabel getLblLB()
    {
        return LblLB;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblLB;
    private javax.swing.JPanel PnlLowerBound;
    // End of variables declaration//GEN-END:variables
}
